name: CI & Mirror Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & Test (Epitech Docker)
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Project
        run: make all

      - name: Run Tests
        run: make tests_run

  coding_style:
    name: Coding Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Coding Style Checker
        run: |
          curl -L https://raw.githubusercontent.com/Epitech/coding-style-checker/refs/heads/main/coding-style.sh -o coding-style.sh
          chmod +x coding-style.sh

      - name: Check coding style result
        run: |
          # If we detect a non-zero count of coding style errors, fail the job
          if ./coding-style.sh . . | grep -Eq '[1-9][0-9]* coding style error\(s\) reported in ' coding-style-reports.log; then
            echo "Coding style errors found."
            exit 1
          else
            echo "No coding style error found."
          fi

  mirror:
    name: Mirror to Epitech Repository
    needs: [build_and_test, coding_style]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Full Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror Repository to Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:

          target_repo_url: git@github.com:EpitechPromo2028/B-NWP-400-NAN-4-1-jetpack-santiago.pidcova.git

          ssh_private_key: ${{ secrets.EPITECH_SSH_KEY }}
