name: CI & Mirror Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build & Test (Epitech Docker)
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Compile Project
        run: make all

      - name: Run Tests
        run: make tests_run

  coding_style:
    runs-on: "ubuntu-latest"
    container:
        image: "ghcr.io/epitech/coding-style-checker:latest"
    steps:
        -   name: "Check coding style"
            run: "/usr/local/bin/check.sh $(pwd) $(pwd)"

        -   name: "Annotate coding-style errors"
            run: |
                status=0
                while IFS= read -r line; do
                    file=$(echo "${line}" | cut -d ':' -f1)
                    pos=$(echo "${line}" | cut -d ':' -f2)
                    type=$(echo "${line}" | cut -d ':' -f3)
                    csid=$(echo "${line}" | cut -d ':' -f4)

                    [[ "${type:1}" == "illegal"* ]] && continue
                    echo "::error file=${file},line=${pos},title=${type:1} ${csid}::${type:1}: ${csid} at ${file}:${pos}"
                    status=1
                done < coding-style-reports.log
                exit "${status}"

  mirror:
    name: Mirror to Epitech Repository
    needs: [build_and_test, coding_style]

    if: ${{ github.repository != 'EpitechPromo2028/B-NWP-400-NAN-4-1-jetpack-santiago.pidcova' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Full Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror Repository to Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:

          target_repo_url: git@github.com:EpitechPromo2028/B-NWP-400-NAN-4-1-jetpack-santiago.pidcova.git

          ssh_private_key: ${{ secrets.EPITECH_SSH_KEY }}
